#ifndef TYPE_TOKEN_HPP
#define TYPE_TOKEN_HPP

#include <iostream>

enum class TypeToken {
  WORKER_PROCESS = 0,
  PID = 1,
  ERROR_LOG = 2,
  GEO_IP_COUNTRY = 3,
  PROXY_CACHE = 4,
  PROXY_CACHE_USE_STALE = 5,
  GZIP = 6,
  GZIP_TYPES = 7,
  REQUEST_TIMEOUT = 8,
  UPLOAD_DIR = 9,
  LIMIT_RED_ZONE = 10,
  PROXY_SET_HEADER = 11,
  PROXY_CACHE_VALID = 12,
  SERVER_NAME = 13,
  SSL_CERTIFICATE = 14,
  SSL_CERTIFICATE_KEY = 15,
  INCLUDE = 16,
  INDEX = 17,
  ROOT = 18,
  LISTEN = 19,
  CLIENT_MAX_BODY_SIZE = 20,
  URL_LOCATION = 21,
  PROXY_PASS = 22,
  ALIAS = 23,
  TRY_FILES = 24,
  ERROR_PAGE = 25,
  ACCESS_LOG = 26,
  DENY = 27,
  CGI = 28,
  REWRITE = 29,
  AUTO_INDEX = 30,
  RETURN = 31,
  SERVER = 32,
  HTTP = 33,
  LOCATION = 34,
  OPEN_BRACKET = 35,
  CLOSING_BRACKET = 36,
  DEFAULT = 37,
  PROXY_CACHE_PATH = 38,
  ALLOW_METHODS = 39,
  VALUE = 40
};

std::ostream &operator<<(std::ostream &outStream, const TypeToken &type);

#endif
