name: Run compile check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run build inside Docker container
      uses: docker://gcc:latest
      with:
        entrypoint: "/bin/bash"
      run: |
        apt-get update && apt-get install -y make

    - name: Build with make
      run: |
        make build