name: C++ Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: run clang-format linter
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'hpp,cpp,tpp,ipp'
        clangFormatVersion: 16 
        style: 'Google'
        inplace: false


    - name: reviewdog
      uses: reviewdog/action-clang-format@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workdir: '.'
        clang_format_flags: '--style=Google'
        fail_on_error: true
        reporter: github-pr-review
        # Add the correct error format
        errorformat: '%f:%l:%c: %m'  
