name: C++ Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: run clang-format linter
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'hpp,cpp,tpp,ipp'
        clangFormatVersion: 16 
        style: 'Google'
        inplace: false

    - name: reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: run reviewdog
      run: |
        reviewdog -f=clang-format-diff -name="clang-format" -reporter=github-pr-review -level=error -diff="git diff HEAD^"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
