name: C++ Linter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install python dependencies
      run: sudo apt-get install python3-setuptools
    - name: run clang-format linter
      uses: LLVM-Mirror/clang-format-lint-action@v1
      with:
        source: '.'
        extensions: 'hpp,cpp,tpp,ipp'
        clangFormatVersion: 16 
        style: 'Google'
