name: C++ Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: run clang-format linter
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'hpp,cpp,tpp,ipp'
        clangFormatVersion: 16 
        style: 'Google'
        checkFormat: true

    - name: reviewdog
      uses: reviewdog/action-setup@v1.3.0
      with:
        github_token: ${{ secrets.TOKEN }}
        workdir: '.'
        clang_format-flags: '--style=Google'
        fail_on_error: true
        reporter: github-pr-review
