name: Run checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Siege
      run: |
        sudo apt-get update
        sudo apt-get install -y procps net-tools siege ulimit

    - name: Build with make
      run: |
        make re

    - name: Increase file descriptor limit
      run: |
        ulimit -n 65536

    - name: Run our webserver
      run: |
        ./webserv&

    - name: Wait until server is ready
      run: |
        for i in {1..10}; do
          curl -s localhost:8080 && break
          sleep 2
        done

    - name: curl localhost
      run: |
        curl localhost:8080

    - name: Run Siege stress test
      run: |
        siege -b -c10 -t1m http://localhost:8080

    - name: Check server memory usage
      run: |
        ps aux | grep webserv

    - name: Monitor memory for leaks
      run: |
        pmap $(pgrep webserv) | tail -n 1

    - name: Check hanging connections
      run: |
        netstat -an | grep :8080
